### PR TITLE
adds expand-to-full-markup functionality to event objective lists.

### PR DESCRIPTION
**Pull request by stopfstedt**

### CODE REVIEW

**Comment by dartajax** [comment]
pretty cool

**Comment by dartajax** [comment]
one thing I noticed - it goes like ...

- collapsed objective 
- collapsed objective
- collapsed objective 

- not collapsed objective 

- collapsed objective 
- collapsed objective 
- collapsed objective

- not collapsed objective 

- collapsed objective 
- collapsed objective

**Comment by stopfstedt** [comment]
> one thing I noticed - it goes like ...
> 
> collapsed objective
> collapsed objective
> collapsed objective
> 
> not collapsed objective
> 
> collapsed objective
> collapsed objective
> collapsed objective
> 
> not collapsed objective
> 
> collapsed objective
> collapsed objective

thanks, i'll look into it. will need to do the alternative sorted list of objectives as well.

**Comment by stopfstedt** [comment]
superseded by  https://github.com/ilios/common/pull/2249

**Pull request closed without merging**
