### PR TITLE
Use resources for course instructors visualizations

### PR DESCRIPTION
**Pull request by stopfstedt**
this corrects:
- the display number of instructional minutes across the entire course per instructor,
- the calculation of percentage of how much instructional time each instructor, compared against the total sum of instructional time in the given course

it improves:
- the labeling of chart bars: show minutes instead of the less meaningful percentage value

### CODE REVIEW

**Comment by dartajax** [comment]
image

**Review by jrjohnson — APPROVED** [review]
I ❤️ these tests!

**Comment by stopfstedt** [comment]
> image

wrong visualization my dude. this  course > session types, not course > instructor > session types. you want to look at the latter.

**Review by dartajax — APPROVED** [review]
it looks good

**Pull request merged**
