### PR TITLE
Update to Froala v3

### PR DESCRIPTION
**Pull request by jrjohnson**
Looks very nearly the same. Will need some user testing to detect any flaws in the new version.

Todo:
- [x] disable tracking beacon
- [x] figure out why license key is not working
- [x] correct z-indexing
- [x] remove current default link search options, and replace with https://www.ncbi.nlm.nih.gov/pubmed/

### CODE REVIEW

**Comment by saschaben** [comment]
notes on update:

for link selection feature:
 - correct z-indexing
 - remove current default link search options, and replace with `https://www.ncbi.nlm.nih.gov/pubmed/`

**Comment by dartajax** [comment]
image

**Comment by jrjohnson** [comment]
Seems to be an issue on common and not a change in this PR. Merge away!

**Comment by dartajax** [comment]
Font issue was a common issue not Froala upgrade issue.

**Pull request merged**
