### PR TITLE
A Few Less Moments

### PR DESCRIPTION
**Pull request by jrjohnson**
Targeting `moment-format` in templates to replace with the locale aware `format-date`. The only downside of this is that we loose the ordinal suffixes on dates (1st, 3rd, etc). Those aren't part of the date format spec at this time. If that's too much to give up we can do some custom helper formatting for those locations.

### CODE REVIEW

**Review by stopfstedt — APPROVED** [review]
LGTM

**Review by stopfstedt — COMMENTED** [review]
@jrjohnson this LGTM.

but i found three more instances of `{{moment-format}}` in templates, do you want to deal with them in this PR or wait until later?

```
stefan@pittiplatsch: ~/dev/projects/common on few-less-moments[$]
$ grep -r 'moment-format' addon
addon/components/sessions-grid.hbs:                {{moment-format
addon/components/offering-form.hbs:                        (eq (moment-format this.startDate "d") obj.day)
addon/components/offering-form.hbs:                      disabled={{eq (moment-format this.startDate "d") obj.day}}

```

**Comment by jrjohnson** [comment]
Whoops, I'll fix those as well and get them all in this PR, thanks!

**Review by dartajax — APPROVED** [review]
I saw the screen shots in Spanish and they looked good so I approve.

**Review by stopfstedt — APPROVED** [review]

**Pull request merged**
