### PR TITLE
Updates to week at a glance

### PR DESCRIPTION
**Pull request by jrjohnson**
Fixes requested at https://github.com/ilios/frontend/issues/3041

### CODE REVIEW

**Comment by saschaben** [comment]
- truncation looks good. **PASS**
- shifted location of instructor looks good. **PASS**
- LM notes when set to "show to students" are not showing, in either week at a glance, or in event detail page. **FAIL**

**Comment by jrjohnson** [comment]
Can you give me the course / session you set notes on so I can take a look at what is coming in over the API?

**Comment by saschaben** [comment]
https://ilios3-demo.ucsf.edu/courses/1116/sessions/32281

(https://ilios3-demo.ucsf.edu/events/U20170707O91441)

**Comment by jrjohnson** [comment]
Good catch, notes were only showing up for citation LMs, Should be fixed now.

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit f64eef3dad7ab4a60fbd53e75343665970efd756

https://deploy-preview-4--ilios-common.netlify.com

**Comment by saschaben** [comment]
looks good.

adding a new ticket to address the absence of notes in the calendar event detail page.

**Comment by saschaben** [comment]
👍

**Pull request merged**
