### PR TITLE
Dedupe pre post requisites

### PR DESCRIPTION
**Pull request by stopfstedt**
refs ilios/frontend#4328

selection_313

selection_314

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview for *ilios-common* ready!

Built with commit 6c488666c72fed11351fc68e4201719886ace0b8

https://deploy-preview-528--ilios-common.netlify.com

**Comment by jrjohnson** [comment]
I think at this early stage it can go without the <show all> button. Maybe `Due before ardvark (mm/dd/yy) and 14 later events.`?

**Comment by stopfstedt** [comment]
> I think at this early stage it can go without the button. Maybe `Due before ardvark (mm/dd/yy) and 14 later events.`?

_later_ is not necessarily the case, they could be running at the same time. but i'll take it.

**Comment by saschaben** [comment]
couple comments:
1) the "show all" button is sort of intrusive/ugly in this context. Maybe instead a clickable icon? bacon?
2) I think the wording we need is "with XX more offerings"
thoughts?

**Comment by stopfstedt** [comment]
> couple comments:
> 
> 1. the "show all" button is sort of intrusive/ugly in this context. Maybe instead a clickable icon? bacon?
> 2. I think the wording we need is "with XX more offerings"
>    thoughts?

re: 1. yes on :bacon: !! srsly tho, i'm hearing "no expando" from @jrjohnson. what to do?
re: 2. agreed.

**Comment by stopfstedt** [comment]
selection_315

next iteration, _no expando_.

@saschaben @jrjohnson any comments before i back this up with tests?

**Comment by jrjohnson** [comment]
While I think we'll add expansion it isn't necessary now (IMO). I do think we need to express that the one you're seeing is the earliest version. Otherwise you will really want to see the rest to know how we picked.

**Pull request merged**
