### PR TITLE
give grid columns more room to breathe.

### LINKED ISSUE #2055: course overview: editinplace controls don't fit into their space
space these controls out a bit more. 

image

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #2055 

since this is a global style change, i  reviewed and included screenshots of affected components/areas in both common and frontend

course-overview
course-summary-header
program-overview
report-overview
sequence-block-overview
session-overview

### CODE REVIEW

**Review by dartajax — COMMENTED** [review]
image


image

**Comment by stopfstedt** [comment]
@dartajax  see https://github.com/ilios/common/pull/2058

**Review by jrjohnson — CHANGES_REQUESTED** [review]
This will bump small tablets down to a one column layout. That isn't a big problem, but I think we probably need to split this into a query for tablets that evenly decides into two 350px columns and change this to use [for-laptop-and-up](https://github.com/ilios/common/blob/master/app/styles/ilios-common/mixins/media.scss#L13) which has more room 3+ 400px columns.

**Comment by stopfstedt** [comment]
> This will bump small tablets down to a one column layout. That isn't a big problem, but I think we probably need to split this into a query for tablets that evenly decides into two 350px columns and change this to use [for-laptop-and-up](https://github.com/ilios/common/blob/master/app/styles/ilios-common/mixins/media.scss#L13) which has more room 3+ 400px columns.

handled. 

for reference, here is how the course overview looks now on tablets:

image
 
i checked all other areas that use those styles again, and the layout works there as well.

**Review by jrjohnson — APPROVED** [review]

**Review by dartajax — APPROVED** [review]

**Pull request merged**
