### PR TITLE
Switch to pnpm

### PR DESCRIPTION
**Pull request by jrjohnson**
Improved peer dependency resolution, faster with a local package cache, and the first step on our way to moving this into a mono repo and v2 add-on format.

### CODE REVIEW

**Review by stopfstedt — APPROVED** [review]

**Comment by stopfstedt** [comment]
rebased against `master`.

**Comment by dartajax** [comment]
I'd love to merge this but alas cannot at this point in time.

image

**Review by stopfstedt — APPROVED** [review]
code looks good. i click-tested course start/end-date, seems to hold up after the change.

LGTM.

**Comment by dartajax** [comment]
I'd be glad to merge this.

**Comment by jrjohnson** [comment]
@dartajax this is ready for testing. Paying particular attention to course start / end date. I had to rebase, but once tests pass and your tests pass it's ready to merge as well.

**Review by dartajax — APPROVED** [review]
This looks good to me. I did a fair amount of testing on start and end date - course level. Gonna merge.

**Pull request merged**
